---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
# ConfigMap for Promtail configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: logging
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.logging.svc.cluster.local:3100/loki/api/v1/push
        # If Loki is outside cluster, use external URL:
        # - url: http://<your-loki-ip>:3100/loki/api/v1/push

    scrape_configs:
      # Scrape all pod logs
      - job_name: kubernetes-pods
        kubernetes_sd_configs:
          - role: pod
        pipeline_stages:
          - cri: {}
        relabel_configs:
          # Only scrape pods that are running
          - source_labels:
              - __meta_kubernetes_pod_phase
            regex: Pending|Succeeded|Failed
            action: drop
          
          # Add namespace label
          - source_labels:
              - __meta_kubernetes_namespace
            target_label: namespace
          
          # Add pod name label
          - source_labels:
              - __meta_kubernetes_pod_name
            target_label: pod
          
          # Add container name label
          - source_labels:
              - __meta_kubernetes_pod_container_name
            target_label: container
          
          # Add node name label
          - source_labels:
              - __meta_kubernetes_pod_node_name
            target_label: node
          
          # Set the log path
          - source_labels:
              - __meta_kubernetes_pod_uid
              - __meta_kubernetes_pod_container_name
            target_label: __path__
            separator: /
            replacement: /var/log/pods/*$1/*.log

---
# ServiceAccount for Promtail
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail
  namespace: logging

---
# ClusterRole for Promtail
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - watch
      - list

---
# ClusterRoleBinding for Promtail
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail
subjects:
  - kind: ServiceAccount
    name: promtail
    namespace: logging

---
# DaemonSet for Promtail
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail
      containers:
        - name: promtail
          image: grafana/promtail:3.5.5
          args:
            - -config.file=/etc/promtail/promtail.yaml
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
          ports:
            - containerPort: 9080
              name: http-metrics
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
            requests:
              memory: 100Mi
              cpu: 100m
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: config
          configMap:
            name: promtail-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
      tolerations:
        - effect: NoSchedule
          operator: Exists

---
# Service for Promtail metrics
apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: logging
  labels:
    app: promtail
spec:
  selector:
    app: promtail
  ports:
    - port: 9080
      targetPort: 9080
      name: http-metrics
  type: ClusterIP